[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100
target-version = "py311"
select = ["E", "F", "I", "UP", "B"]
exclude = ["venv", ".venv", "build", "dist"]

[tool.ruff.lint.isort]
known-first-party = ["src"]